In [91]:
import pandas as pd
import numpy as np
import sqlite3
from sqlalchemy import create_engine

# connection build
mydb = create_engine('mysql://root:GS9-lO24a@localhost:3306/bincomphptest')

# sql query
query1 = 'SELECT * FROM agentname'
query2 = 'SELECT * FROM announced_lga_results'
query3 = 'SELECT * FROM polling_unit'
query4 = 'SELECT * FROM states'
query5 = 'SELECT * FROM ward'
query6 = 'SELECT * FROM party'
query7 = 'SELECT * FROM lga'
query8 = 'SELECT * FROM announced_ward_results'
query9 = 'SELECT * FROM announced_state_results'
query10 = 'SELECT * FROM announced_pu_results'

# convert sql query to dataframe
agentname = pd.read_sql(query1, mydb)
alr = pd.read_sql(query2, mydb)
pollingunit = pd.read_sql(query3, mydb)
states = pd.read_sql(query4, mydb)
ward = pd.read_sql(query5, mydb)
party = pd.read_sql(query6, mydb)
lga = pd.read_sql(query7, mydb)
awr = pd.read_sql(query8, mydb)
asr = pd.read_sql(query9, mydb)
apr = pd.read_sql(query10, mydb)

alr.to_csv('alr.csv')
agentname.to_csv('agentname.csv')
pollingunit.to_csv('pollingunit.csv')
states.to_csv('states.csv')
ward.to_csv('ward.csv')
party.to_csv('party.csv')
lga.to_csv('lga.csv')
awr.to_csv('awr.csv')
asr.to_csv('asr.csv')
apr.to_csv('apr.csv')

In [92]:
agentname.head()

name_id  firstname lastname                 email        phone  \
0        1  Christian  Emenike  christian@bincom.net  08034699500   
1        2      Ngozi  Emenike  biggysmalls@home.net  08089003444   
2        3   Chinyere  Emenike  chinyere@emenike.net  07034532310   
3        4   Chimezie  Emenike  chimezie@emenike.net  07034532322   

   pollingunit_uniqueid  
0                     1  
1                     2  
2                     1  
3                     2

In [93]:
agentname.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   name_id               4 non-null      int64 
 1   firstname             4 non-null      object
 2   lastname              4 non-null      object
 3   email                 4 non-null      object
 4   phone                 4 non-null      object
 5   pollingunit_uniqueid  4 non-null      int64 
dtypes: int64(2), object(4)
memory usage: 320.0+ bytes


In [94]:
agentname.shape

(4, 6)

In [95]:
alr.head()

result_id lga_name party_abbreviation  party_score entered_by_user  \
0          1       33                PDP        78129                   
1          2       33                DPP        15248                   
2          3       33                ACN         8597                   
3          4       33                PPA          797                   
4          5       33                CDC        79513                   

         date_entered user_ip_address  
0 2011-04-27 09:46:05   192.168.1.110  
1 2011-04-27 09:46:05   192.168.1.110  
2 2011-04-27 09:46:05   192.168.1.110  
3 2011-04-27 09:46:05   192.168.1.110  
4 2011-04-27 09:46:05   192.168.1.110

In [96]:
alr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   result_id           225 non-null    int64         
 1   lga_name            225 non-null    object        
 2   party_abbreviation  225 non-null    object        
 3   party_score         225 non-null    int64         
 4   entered_by_user     225 non-null    object        
 5   date_entered        225 non-null    datetime64[ns]
 6   user_ip_address     225 non-null    object        
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 12.4+ KB


In [97]:
alr.shape

(225, 7)

In [98]:
pollingunit.head()

uniqueid  polling_unit_id  ward_id  lga_id  uniquewardid  \
0         8                6        8      17           181   
1         9                4        1      19           194   
2        10                5        1      19           194   
3        11                5        3      34           244   
4        12                1        4      21           220   

  polling_unit_number              polling_unit_name  \
0           DT1708006             Sapele Ward 8 PU _   
1           DT1901004       Primary School in Aghara   
2           DT1401005  Ishere Primary School  Aghara   
3           DT3403005           Igini Primary School   
4           DT2104001           Umukwapa poll unit 1   

       polling_unit_description          lat         long entered_by_user  \
0                          None   5.59371889  5.999311165            None   
1      Primary School in Aghara  5.599585986  6.001336288            None   
2  Ishere Primary School Aghara  5.595722496   5.99961724            None   
3                    Esisi Road  5.602005475  6.001611141            None   
4                          None  5.596383741   5.99023883            None   

  date_entered user_ip_address  
0         None            None  
1         None            None  
2         None            None  
3         None            None  
4         None            None

In [174]:
ward.head()

uniqueid  ward_id        ward_name  lga_id ward_description  \
0         1        2       Aba - Unor       2       Aba - Unor   
1         2        8            Ejeme       2            Ejeme   
2         3        9  Isheagu - Ewulu       2  Isheagu - Ewulu   
3         4        7           Nsukwa       2           Nsukwa   
4         5        2  Ogwashi - Uku I       2  Ogwashi - Uku I   

  entered_by_user date_entered user_ip_address  
0          Bincom         None       127.0.0.1  
1          Bincom         None       127.0.0.1  
2          Bincom         None       127.0.0.1  
3          Bincom         None       127.0.0.1  
4          Bincom         None       127.0.0.1

In [177]:
lga.head()

uniqueid  lga_id          lga_name  state_id   lga_description  \
0         1       1     Aniocha North        25     Aniocha North   
1         2       2   Aniocha - South        25   Aniocha - South   
2         3       5      Ethiope East        25      Ethiope East   
3         4       6      Ethiope West        25      Ethiope West   
4         5       7  Ika North - East        25  Ika North - East   

  entered_by_user date_entered user_ip_address  
0          Bincom         None       127.0.0.2  
1          Bincom         None       127.0.0.1  
2          Bincom         None       127.0.0.5  
3          Bincom         None       127.0.0.6  
4          Bincom         None       127.0.0.8

In [178]:
lga['lga_id'].unique() # 37

array([ 1,  2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 31, 32, 33, 34, 35], dtype=int64)

In [176]:
ward['ward_id'].unique() #new 15

array([ 2,  8,  9,  7,  3,  1,  4,  5,  6, 11, 10,  0, 12, 14, 13],
      dtype=int64)

In [170]:
pollingunit['polling_unit_id'].unique()

array([ 6,  4,  5,  1, 16, 13,  9,  7, 11,  3,  2, 14,  8, 12, 10, 15, 17,
       21, 18, 51, 31,  0], dtype=int64)

In [173]:
pollingunit['ward_id'].unique()

array([ 8,  1,  3,  4,  7,  2,  9, 10, 11,  5,  0,  6, 12], dtype=int64)

In [172]:
pollingunit['lga_id'].unique()

array([17, 19, 34, 21, 22,  7, 35,  6,  1,  9, 15,  2, 10, 31, 13, 11, 32,
        0], dtype=int64)

In [99]:
pollingunit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   uniqueid                  272 non-null    int64 
 1   polling_unit_id           272 non-null    int64 
 2   ward_id                   272 non-null    int64 
 3   lga_id                    272 non-null    int64 
 4   uniquewardid              272 non-null    int64 
 5   polling_unit_number       272 non-null    object
 6   polling_unit_name         272 non-null    object
 7   polling_unit_description  268 non-null    object
 8   lat                       272 non-null    object
 9   long                      272 non-null    object
 10  entered_by_user           221 non-null    object
 11  date_entered              0 non-null      object
 12  user_ip_address           221 non-null    object
dtypes: int64(5), object(8)
memory usage: 27.8+ KB


In [179]:
pollingunit.head()

uniqueid  polling_unit_id  ward_id  lga_id  uniquewardid  \
0         8                6        8      17           181   
1         9                4        1      19           194   
2        10                5        1      19           194   
3        11                5        3      34           244   
4        12                1        4      21           220   

  polling_unit_number              polling_unit_name  \
0           DT1708006             Sapele Ward 8 PU _   
1           DT1901004       Primary School in Aghara   
2           DT1401005  Ishere Primary School  Aghara   
3           DT3403005           Igini Primary School   
4           DT2104001           Umukwapa poll unit 1   

       polling_unit_description          lat         long entered_by_user  \
0                          None   5.59371889  5.999311165            None   
1      Primary School in Aghara  5.599585986  6.001336288            None   
2  Ishere Primary School Aghara  5.595722496   5.99961724            None   
3                    Esisi Road  5.602005475  6.001611141            None   
4                          None  5.596383741   5.99023883            None   

  date_entered user_ip_address  
0         None            None  
1         None            None  
2         None            None  
3         None            None  
4         None            None

In [180]:
ward.head()

uniqueid  ward_id        ward_name  lga_id ward_description  \
0         1        2       Aba - Unor       2       Aba - Unor   
1         2        8            Ejeme       2            Ejeme   
2         3        9  Isheagu - Ewulu       2  Isheagu - Ewulu   
3         4        7           Nsukwa       2           Nsukwa   
4         5        2  Ogwashi - Uku I       2  Ogwashi - Uku I   

  entered_by_user date_entered user_ip_address  
0          Bincom         None       127.0.0.1  
1          Bincom         None       127.0.0.1  
2          Bincom         None       127.0.0.1  
3          Bincom         None       127.0.0.1  
4          Bincom         None       127.0.0.1

In [182]:
lga.head()

uniqueid  lga_id          lga_name  state_id   lga_description  \
0         1       1     Aniocha North        25     Aniocha North   
1         2       2   Aniocha - South        25   Aniocha - South   
2         3       5      Ethiope East        25      Ethiope East   
3         4       6      Ethiope West        25      Ethiope West   
4         5       7  Ika North - East        25  Ika North - East   

  entered_by_user date_entered user_ip_address  
0          Bincom         None       127.0.0.2  
1          Bincom         None       127.0.0.1  
2          Bincom         None       127.0.0.5  
3          Bincom         None       127.0.0.6  
4          Bincom         None       127.0.0.8

In [183]:
apr.head()

result_id party_abbreviation  party_score entered_by_user  \
0        111                PDP          802            Bose   
1        112                DPP          719            Bose   
2        113                ACN          416            Bose   
3        114                PPA          939            Bose   
4        115                CDC          394            Bose   

         date_entered user_ip_address  polling_unit_id  
0 2011-04-26 15:44:03   192.168.1.101                8  
1 2011-04-26 15:44:03   192.168.1.101                8  
2 2011-04-26 15:44:03   192.168.1.101                8  
3 2011-04-26 15:44:03   192.168.1.101                8  
4 2011-04-26 15:44:03   192.168.1.101                8

In [185]:
apr['result_id'].unique()

array([111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
       137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
       150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
       163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
       189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201,
       202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
       215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
       228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
       241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253,
       254, 255, 256, 257, 258, 259, 260], dtype=int64)

In [184]:
apr['polling_unit_id'].unique()

array([ 8,  9, 10, 11, 12, 13, 15, 16, 18, 19, 20, 21, 24, 23, 22, 25, 26,
       27], dtype=int64)

In [101]:
states.head()

state_id state_name
0         1      Abuja
1         2       Abia
2         3    Anambra
3         4  Akwa Ibom
4         5    Adamawa

In [102]:
states.shape

(37, 2)

In [103]:
states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   state_id    37 non-null     int64 
 1   state_name  37 non-null     object
dtypes: int64(1), object(1)
memory usage: 720.0+ bytes


In [104]:
states['state_name']

0           Abuja
1            Abia
2         Anambra
3       Akwa Ibom
4         Adamawa
5          Bauchi
6         Bayelsa
7           Benue
8           Borno
9     Cross River
10         Ebonyi
11            Edo
12          Ekiti
13          Enugu
14          Gombe
15            Imo
16         Jigawa
17         Kaduna
18           Kano
19        Katsina
20          Kebbi
21           Kogi
22          Kwara
23          Delta
24       Nasarawa
25          Niger
26           Ogun
27           Ondo
28           Osun
29            Oyo
30        Plateau
31         Rivers
32         Sokoto
33         Taraba
34           Yobe
35        Zamfara
36          Lagos
Name: state_name, dtype: object

In [105]:
alr['party_abbreviation'].value_counts()

PDP     25
DPP     25
ACN     25
PPA     25
CDC     25
JP      25
ANPP    25
LABO    25
CPP     25
Name: party_abbreviation, dtype: int64

In [106]:
party.head()

id partyid partyname
0   1     PDP       PDP
1   2     DPP       DPP
2   3     ACN       ACN
3   4     PPA       PPA
4   5     CDC       CDC

In [107]:
party.shape

(9, 3)

In [108]:
party.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         9 non-null      int64 
 1   partyid    9 non-null      object
 2   partyname  9 non-null      object
dtypes: int64(1), object(2)
memory usage: 344.0+ bytes


In [109]:
lga.head()

uniqueid  lga_id          lga_name  state_id   lga_description  \
0         1       1     Aniocha North        25     Aniocha North   
1         2       2   Aniocha - South        25   Aniocha - South   
2         3       5      Ethiope East        25      Ethiope East   
3         4       6      Ethiope West        25      Ethiope West   
4         5       7  Ika North - East        25  Ika North - East   

  entered_by_user date_entered user_ip_address  
0          Bincom         None       127.0.0.2  
1          Bincom         None       127.0.0.1  
2          Bincom         None       127.0.0.5  
3          Bincom         None       127.0.0.6  
4          Bincom         None       127.0.0.8

In [110]:
lga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   uniqueid         25 non-null     int64 
 1   lga_id           25 non-null     int64 
 2   lga_name         25 non-null     object
 3   state_id         25 non-null     int64 
 4   lga_description  25 non-null     object
 5   entered_by_user  25 non-null     object
 6   date_entered     0 non-null      object
 7   user_ip_address  25 non-null     object
dtypes: int64(3), object(5)
memory usage: 1.7+ KB


In [111]:
awr.head()

Empty DataFrame
Columns: [result_id, ward_name, party_abbreviation, party_score, entered_by_user, date_entered, user_ip_address]
Index: []

In [112]:
apr.head()

result_id polling_unit_uniqueid party_abbreviation  party_score  \
0        111                     8                PDP          802   
1        112                     8                DPP          719   
2        113                     8                ACN          416   
3        114                     8                PPA          939   
4        115                     8                CDC          394   

  entered_by_user        date_entered user_ip_address  
0            Bose 2011-04-26 15:44:03   192.168.1.101  
1            Bose 2011-04-26 15:44:03   192.168.1.101  
2            Bose 2011-04-26 15:44:03   192.168.1.101  
3            Bose 2011-04-26 15:44:03   192.168.1.101  
4            Bose 2011-04-26 15:44:03   192.168.1.101

In [113]:
apr.head()

result_id polling_unit_uniqueid party_abbreviation  party_score  \
0        111                     8                PDP          802   
1        112                     8                DPP          719   
2        113                     8                ACN          416   
3        114                     8                PPA          939   
4        115                     8                CDC          394   

  entered_by_user        date_entered user_ip_address  
0            Bose 2011-04-26 15:44:03   192.168.1.101  
1            Bose 2011-04-26 15:44:03   192.168.1.101  
2            Bose 2011-04-26 15:44:03   192.168.1.101  
3            Bose 2011-04-26 15:44:03   192.168.1.101  
4            Bose 2011-04-26 15:44:03   192.168.1.101

In [114]:
apr.shape

(150, 7)

In [115]:
ward.head()

uniqueid  ward_id        ward_name  lga_id ward_description  \
0         1        2       Aba - Unor       2       Aba - Unor   
1         2        8            Ejeme       2            Ejeme   
2         3        9  Isheagu - Ewulu       2  Isheagu - Ewulu   
3         4        7           Nsukwa       2           Nsukwa   
4         5        2  Ogwashi - Uku I       2  Ogwashi - Uku I   

  entered_by_user date_entered user_ip_address  
0          Bincom         None       127.0.0.1  
1          Bincom         None       127.0.0.1  
2          Bincom         None       127.0.0.1  
3          Bincom         None       127.0.0.1  
4          Bincom         None       127.0.0.1

In [116]:
ward.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   uniqueid          263 non-null    int64 
 1   ward_id           263 non-null    int64 
 2   ward_name         263 non-null    object
 3   lga_id            263 non-null    int64 
 4   ward_description  263 non-null    object
 5   entered_by_user   263 non-null    object
 6   date_entered      0 non-null      object
 7   user_ip_address   263 non-null    object
dtypes: int64(3), object(5)
memory usage: 16.6+ KB


Create a page to display the result for any individual polling unit on a web page. Note that the Database you have been given only contains LGA's in Delta State

In [117]:
apr.head()

result_id polling_unit_uniqueid party_abbreviation  party_score  \
0        111                     8                PDP          802   
1        112                     8                DPP          719   
2        113                     8                ACN          416   
3        114                     8                PPA          939   
4        115                     8                CDC          394   

  entered_by_user        date_entered user_ip_address  
0            Bose 2011-04-26 15:44:03   192.168.1.101  
1            Bose 2011-04-26 15:44:03   192.168.1.101  
2            Bose 2011-04-26 15:44:03   192.168.1.101  
3            Bose 2011-04-26 15:44:03   192.168.1.101  
4            Bose 2011-04-26 15:44:03   192.168.1.101

In [118]:
apr['polling_unit_id'] = apr['polling_unit_uniqueid']

In [119]:
apr.drop('polling_unit_uniqueid', axis = 1, inplace=True)

In [120]:
apr.head()

result_id party_abbreviation  party_score entered_by_user  \
0        111                PDP          802            Bose   
1        112                DPP          719            Bose   
2        113                ACN          416            Bose   
3        114                PPA          939            Bose   
4        115                CDC          394            Bose   

         date_entered user_ip_address polling_unit_id  
0 2011-04-26 15:44:03   192.168.1.101               8  
1 2011-04-26 15:44:03   192.168.1.101               8  
2 2011-04-26 15:44:03   192.168.1.101               8  
3 2011-04-26 15:44:03   192.168.1.101               8  
4 2011-04-26 15:44:03   192.168.1.101               8

In [121]:
pollingunit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   uniqueid                  272 non-null    int64 
 1   polling_unit_id           272 non-null    int64 
 2   ward_id                   272 non-null    int64 
 3   lga_id                    272 non-null    int64 
 4   uniquewardid              272 non-null    int64 
 5   polling_unit_number       272 non-null    object
 6   polling_unit_name         272 non-null    object
 7   polling_unit_description  268 non-null    object
 8   lat                       272 non-null    object
 9   long                      272 non-null    object
 10  entered_by_user           221 non-null    object
 11  date_entered              0 non-null      object
 12  user_ip_address           221 non-null    object
dtypes: int64(5), object(8)
memory usage: 27.8+ KB


In [123]:
apr['polling_unit_id'] = pd.to_numeric(apr['polling_unit_id'])

In [124]:
apr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   result_id           150 non-null    int64         
 1   party_abbreviation  150 non-null    object        
 2   party_score         150 non-null    int64         
 3   entered_by_user     150 non-null    object        
 4   date_entered        150 non-null    datetime64[ns]
 5   user_ip_address     150 non-null    object        
 6   polling_unit_id     150 non-null    int64         
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 8.3+ KB


In [131]:
pollResult = pollingunit.merge(apr, on = 'polling_unit_id')[['polling_unit_id', 'result_id', 'party_score','party_abbreviation', 'polling_unit_number', 'polling_unit_name']]
pollResult.shape

(290, 6)

In [133]:
pollResult.to_csv('poll.csv')

In [127]:
pollResult['polling_unit_id'].value_counts()

8     48
13    42
10    42
16    32
11    30
12    30
9     24
21    18
15    16
18     8
Name: polling_unit_id, dtype: int64

In [134]:
pollingunit.head()

uniqueid  polling_unit_id  ward_id  lga_id  uniquewardid  \
0         8                6        8      17           181   
1         9                4        1      19           194   
2        10                5        1      19           194   
3        11                5        3      34           244   
4        12                1        4      21           220   

  polling_unit_number              polling_unit_name  \
0           DT1708006             Sapele Ward 8 PU _   
1           DT1901004       Primary School in Aghara   
2           DT1401005  Ishere Primary School  Aghara   
3           DT3403005           Igini Primary School   
4           DT2104001           Umukwapa poll unit 1   

       polling_unit_description          lat         long entered_by_user  \
0                          None   5.59371889  5.999311165            None   
1      Primary School in Aghara  5.599585986  6.001336288            None   
2  Ishere Primary School Aghara  5.595722496   5.99961724            None   
3                    Esisi Road  5.602005475  6.001611141            None   
4                          None  5.596383741   5.99023883            None   

  date_entered user_ip_address  
0         None            None  
1         None            None  
2         None            None  
3         None            None  
4         None            None

In [135]:
pollResult2 = pollingunit.merge(apr, on = 'polling_unit_id')[['polling_unit_id', 'result_id', 'party_score','party_abbreviation', 'polling_unit_number', 'polling_unit_name', 'lga_id']]
pollResult2.shape

(290, 7)

In [136]:
pollResult2.head()

polling_unit_id  result_id  party_score party_abbreviation  \
0               16        164         1178                PDP   
1               16        165          129                DPP   
2               16        166          406                ACN   
3               16        167          614                PPA   
4               16        168          794                CDC   

  polling_unit_number        polling_unit_name  lga_id  
0           DT2201016  Church in Effurun1 Ovie      22  
1           DT2201016  Church in Effurun1 Ovie      22  
2           DT2201016  Church in Effurun1 Ovie      22  
3           DT2201016  Church in Effurun1 Ovie      22  
4           DT2201016  Church in Effurun1 Ovie      22

In [137]:
pollResult2['lga_id'].value_counts()

31    71
22    50
15    48
34    32
35    32
6     25
21    13
2      7
1      6
17     6
Name: lga_id, dtype: int64

In [141]:
lgaResult2 = lga.merge(pollResult2, on = 'lga_id')[['lga_name','lga_description','party_score','party_abbreviation']]
lgaResult2.shape

(290, 4)

In [142]:
lgaResult2

lga_name   lga_description  party_score party_abbreviation
0       Aniocha North     Aniocha North          802                PDP
1       Aniocha North     Aniocha North          719                DPP
2       Aniocha North     Aniocha North          416                ACN
3       Aniocha North     Aniocha North          939                PPA
4       Aniocha North     Aniocha North          394                CDC
..                ...               ...          ...                ...
285  Warri South West  Warri South West          624                PPA
286  Warri South West  Warri South West          375                CDC
287  Warri South West  Warri South West          952                 JP
288  Warri South West  Warri South West          583               ANPP
289  Warri South West  Warri South West         1012               LABO

[290 rows x 4 columns]

In [156]:
lgaResult2['lga_name'].unique()

array(['Aniocha North', 'Aniocha - South', 'Ethiope West',
       'Oshimili - South', 'Sapele', 'Ukwuani', 'Uvwie', 'Bomadi',
       'Warri South', 'Warri South West'], dtype=object)

In [154]:
lgaResult2.to_csv('lgaresults.csv')

In [153]:
lgaResult2[lgaResult2['party_abbreviation'] == 'PDP']

lga_name   lga_description  party_score party_abbreviation
0       Aniocha North     Aniocha North          802                PDP
6     Aniocha - South   Aniocha - South          853                PDP
13       Ethiope West      Ethiope West          853                PDP
20       Ethiope West      Ethiope West          802                PDP
26       Ethiope West      Ethiope West          306                PDP
32       Ethiope West      Ethiope West          306                PDP
38   Oshimili - South  Oshimili - South         1178                PDP
46   Oshimili - South  Oshimili - South          285                PDP
52   Oshimili - South  Oshimili - South          621                PDP
58   Oshimili - South  Oshimili - South          802                PDP
64   Oshimili - South  Oshimili - South          561                PDP
70   Oshimili - South  Oshimili - South          236                PDP
78   Oshimili - South  Oshimili - South          287                PDP
86             Sapele            Sapele          802                PDP
92            Ukwuani           Ukwuani          853                PDP
99            Ukwuani           Ukwuani          621                PDP
105             Uvwie             Uvwie         1178                PDP
113             Uvwie             Uvwie         1178                PDP
121             Uvwie             Uvwie          853                PDP
128             Uvwie             Uvwie          621                PDP
134             Uvwie             Uvwie          802                PDP
140             Uvwie             Uvwie          802                PDP
146             Uvwie             Uvwie          480                PDP
155            Bomadi            Bomadi         1178                PDP
163            Bomadi            Bomadi          285                PDP
169            Bomadi            Bomadi          621                PDP
175            Bomadi            Bomadi          802                PDP
181            Bomadi            Bomadi          306                PDP
187            Bomadi            Bomadi          561                PDP
193            Bomadi            Bomadi          236                PDP
201            Bomadi            Bomadi          287                PDP
209            Bomadi            Bomadi          480                PDP
218            Bomadi            Bomadi         1009                PDP
226       Warri South       Warri South          853                PDP
233       Warri South       Warri South          853                PDP
240       Warri South       Warri South          285                PDP
246       Warri South       Warri South          306                PDP
252       Warri South       Warri South          306                PDP
258  Warri South West  Warri South West          285                PDP
264  Warri South West  Warri South West          621                PDP
270  Warri South West  Warri South West          802                PDP
276  Warri South West  Warri South West          561                PDP
282  Warri South West  Warri South West          236                PDP

In [158]:
a = lgaResult2.groupby(by = 'lga_name')['party_score'].sum()

In [168]:
a

lga_name
Aniocha - South      4740
Aniocha North        3369
Bomadi              39690
Ethiope West        15553
Oshimili - South    26947
Sapele               3369
Ukwuani              8458
Uvwie               28661
Warri South         20598
Warri South West    19367
Name: party_score, dtype: int64

In [166]:
b = 'Bomadi'

In [167]:
a[b]

39690

In [143]:
lgaResult2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 290 entries, 0 to 289
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   lga_name            290 non-null    object
 1   lga_description     290 non-null    object
 2   party_score         290 non-null    int64 
 3   party_abbreviation  290 non-null    object
dtypes: int64(1), object(3)
memory usage: 11.3+ KB


In [147]:
aa = lgaResult2.groupby('party_abbreviation').sum()

C:\Users\Gbemi\AppData\Local\Temp\ipykernel_12116\3337702719.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  aa = lgaResult2.groupby('party_abbreviation').sum()


In [148]:
aa

party_score
party_abbreviation             
ACN                       27946
ANPP                      13492
CDC                       17127
CPP                         184
DPP                       32454
JP                        15248
LABO                       7935
PDP                       26955
PPA                       29411

In [129]:
lga.shape

(25, 8)

In [130]:
states

state_id   state_name
0          1        Abuja
1          2         Abia
2          3      Anambra
3          4    Akwa Ibom
4          5      Adamawa
5          6       Bauchi
6          7      Bayelsa
7          8        Benue
8          9        Borno
9         10  Cross River
10        12       Ebonyi
11        13          Edo
12        14        Ekiti
13        15        Enugu
14        16        Gombe
15        17          Imo
16        18       Jigawa
17        19       Kaduna
18        20         Kano
19        21      Katsina
20        22        Kebbi
21        23         Kogi
22        24        Kwara
23        25        Delta
24        26     Nasarawa
25        27        Niger
26        28         Ogun
27        29         Ondo
28        30         Osun
29        31          Oyo
30        32      Plateau
31        33       Rivers
32        34       Sokoto
33        35       Taraba
34        36         Yobe
35        37      Zamfara
36       251        Lagos

Create a page to be used to store results for ALL parties for a new polling unit.